### ISSUE TITLE
unknown callback id

### ISSUE THREAD

**Issue by heapwolf** [hij1nx/level-2pc#1]
When running the test I get this message from `rpc-stream` module...

```
ERROR: unknown callback id: 2 []
ERROR: unknown callback id: 2 []
```

It appears to be from recursing the connect function which is defined as a callback for the rpc client. Any ideas @dominictarr?

**Comment by heapwolf** [comment]
ping @dominictarr

**Comment by dominictarr** [comment]
hey sorry, have been offline.

my guess is that it's calling the cb twice. it deletes the cb after, so it won't be a known cb after that.

**Comment by dominictarr** [comment]
https://github.com/dominictarr/rpc-stream/blob/master/index.js#L64-L78

**Comment by heapwolf** [comment]
yep, so i forked that and commented out the line of code that console logs the warning. I think it might be giving false positives becuse my callback is inside a recursive function. Like this in pseudo code...

``` js
!outerMethod() {
  remoteMethod(function() {
    outerMethod(); // called once more.
  });
}();
```

**Comment by dominictarr** [comment]
oh, you can't call a cb like that. but if you put remote method on the api then you can call it lots, else, you should use a stream for that kind of api.

**Comment by dominictarr** [comment]
oh, for a stream you'd need mux-demux or multilevel, but now days i'd recommend using muxrpc which combines (pull-)streams async and events in a more efficient way.

**Comment by heapwolf** [comment]
A stream isn't really appropriate because it's only called twice. interestingly, the remoteMethod _is_ on the api, and it works totally fine, it just prints the error.

**Comment by heapwolf** [comment]
I was also able to fix this from level-2pc by changing logic slightly. maybe I'll try to come up with some reduced use case that shows why I think this error reporting produces false positives.

**Comment by dominictarr** [comment]
cool
